version: '3.2'

networks:
  backend:
    driver: bridge

volumes:
  home:
  mosquitto:

services:
  app: &app-service
    image: registry.gitlab.explabs.ru:5005/web-development/pacsman/pacsman-backend:${CURRENT_IMAGES_TAG:-master}
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./.docker/app/app-entrypoint.sh:/app-entrypoint.sh:ro
      - ./:/app:cached
      - home:/home/user:cached
    env_file:
      - ./.env.docker
    environment:
      - "HOME=/home/user"
      - "APP_FORCE_HTTPS=true"
      - "STARTUP_WAIT_FOR_SERVICES=true"
      - "APP_ENV=local"
      - "APP_DEBUG=true"
      - "APP_LOG_LEVEL=debug"
    ports:
      - '4001:80'
      - '4002:443'
    command: 'rr serve -v -d -c /app/.rr.local.yml'
    networks:
      - backend

  queue:
    <<: *app-service
    user: "${CURRENT_USER:-0:0}"
    environment:
      STARTUP_DELAY: 5
    command: 'php /app/artisan queue:work --memory=64'
    ports: []

