version: "3.8"

services:
  app: &app-service
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: registry.gitlab.explabs.ru:5005/web-development/fitness/fitness-backend:${CURRENT_IMAGES_TAG:-latest}
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./:/var/www/html:cached
      - home:/home/user:cached
    env_file:
      - .env.docker
    environment:
      - "HOME=/home/user"
      - "APP_ENV=local"
      - "APP_DEBUG=true"
      - "APP_LOG_LEVEL=debug"
      - "DB_CONNECTION=pgsql"
      - "DB_HOST=postgres"
      - "DB_DATABASE=${POSTGRES_DB}"
      - "DB_USERNAME=${POSTGRES_USER}"
      - "DB_PASSWORD=${POSTGRES_PASSWORD}"
      - "QUEUE_CONNECTION=redis"
      - "REDIS_HOST=redis"
    ports:
      - 8000:5000
    depends_on:
      - postgres
      - redis
    networks:
      - backend

  # queue:
  #   <<: *app-service
  #   user: "${CURRENT_USER:-0:0}"
  #   command: 'php artisan horizon'
  #   ports: []
  #   depends_on:
  #     - app

  schedule:
    <<: *app-service
    user: "${CURRENT_USER:-0:0}"
    command: './schedule.sh'
    ports: []
    depends_on:
      - app

  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    tty: true
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env.docker
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend

  redis:
    image: redis:alpine
    networks:
      - backend

  adminer:
    image: adminer:latest
    restart: always
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=postgres
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=${POSTGRES_DB}
      - ADMINER_DESIGN=nette
      - ADMINER_PLUGINS=tables-filter tinymce
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  home:
  dbdata:
    driver: local

networks:
  backend:
    driver: bridge
