version: '3.7'

networks:
  backend:
    driver: bridge

volumes:
  home:
  postgres:
    driver: "local"

services:
  app: &app-service
    image: registry.gitlab.explabs.ru:5005/web-development/fitness/fitness-backend:${CURRENT_IMAGES_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./.docker/app/app-entrypoint.sh:/app-entrypoint.sh:ro
      - ./:/app:cached
      - home:/home/user:cached
    env_file:
      - ./.env.docker
    environment:
      - "HOME=/home/user"
      - "APP_FORCE_HTTPS=true"
      - "STARTUP_WAIT_FOR_SERVICES=true"
      - "APP_ENV=local"
      - "APP_DEBUG=true"
      - "APP_LOG_LEVEL=debug"
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_DATABASE=${POSTGRES_DB}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '4001:80'
      - '4002:443'
    command: 'rr serve -v -d -c /app/.rr.local.yml'
    networks:
      - backend

  queue:
    <<: *app-service
    user: "${CURRENT_USER:-0:0}"
    environment:
      STARTUP_DELAY: 5
    command: 'php /app/artisan queue:work --memory=64'
    ports: []

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - 54320:5432
    networks:
      - backend

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=postgres
      - ADMINER_DEFAULT_DB_HOST=postgres
      - ADMINER_DEFAULT_DB_NAME=${POSTGRES_DB}
      - ADMINER_DESIGN=nette
      - ADMINER_PLUGINS=tables-filter tinymce
    ports:
      - 8080:9000
    networks:
      - backend

